name: final_project
channels:
  - conda-forge
  - nodefaults
dependencies:
  # defaults
  - python>=3.8
  - pip
  - pre-commit
  - pytest>=6
  - pytest-cov
  - setuptools-scm
  # data
  - pandas
  - numpy<2
  - dask-ml
  - ydata-profiling
  # interactive
  - ipykernel
  # plots
  - matplotlib
  - nbformat
  # ml
  - glum
  - lightgbm
  - scikit-learn
  - dalex
